#!/bin/sh

# Copyright 2025 Genesis Corporation
#
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

mount -t proc      proc      /proc
mount -t sysfs     sysfs     /sys
mount -t tmpfs     tmpfs     /tmp
mount -t devtmpfs  devtmpfs  /dev

export PYTHONHOME=/
export PYTHON_VER="3.10"
export PYTHONPATH="$PYTHONPATH:/lib/:/lib/python$PYTHON_VER/site-packages/genesis_seed"
export SEED_OS_AGENT="/lib/python$PYTHON_VER/site-packages/genesis_seed/genesis_seed/cmd/agent.py"


# Check available interfaces and bring them up
for iface_path in /sys/class/net/eth*; do
    # The glob returns the pattern itself if no files match.
    # This check ensures we only proceed if an interface was actually found.
    if [ ! -e "$iface_path" ]; then
        continue
    fi
    iface=$(basename "$iface_path")
    ifconfig "$iface" up
    udhcpc -i "$iface" -n -s /bin/ifup.sh
done

echo "GENESIS SEED OS !!!"
python3 $SEED_OS_AGENT
sh
