name: build

on:
  pull_request:
  workflow_dispatch:
    inputs:
      build_target:
        description: 'Build target'
        required: true
        default: 'manual'
        type: choice
        options:
        - manual

env:
  PROJECT_NAME: seed_os
  REPO_ENDPOINT_PUT: http://10.20.0.1:8082

jobs:
  Build:
    runs-on: self-hosted
    if : ${{ github.actor != 'dependabot[bot]' }}
    strategy:
      fail-fast: true
    steps:
#      - name: Install deps
#        run: sudo apt install --yes liblzma-dev bison flex libelf-dev libssl-dev
      - uses: actions/checkout@v4
        with:
          fetch-depth: 30
      - name: Build binaries(Kernel, Busybox, Python, Initrd) on Self-Hosted runner
        run: |
          make clean && make && make ipxe
      - name: Upload kernel and initrd to GC repository
        run: |
          set -eux
          
          source ~/.profile
          VERSION="$(genesis get-version .)"
          
          curl -X PUT --upload-file ./initrd.img \
            $REPO_ENDPOINT_PUT/${PROJECT_NAME}/${VERSION}/initrd.img
          curl -X PUT --upload-file ./vmlinuz \
            $REPO_ENDPOINT_PUT/${PROJECT_NAME}/${VERSION}/vmlinuz
          curl -X PUT --upload-file ./undionly.kpxe \
            $REPO_ENDPOINT_PUT/${PROJECT_NAME}/${VERSION}/undionly.kpxe

      - name: Upload to latest on tag
        if: github.ref_type == 'tag'
        run: |
          set -eux
          
          curl -X PUT --upload-file ./initrd.img \
            $REPO_ENDPOINT_PUT/${PROJECT_NAME}/latest/initrd.img
          curl -X PUT --upload-file ./vmlinuz \
            $REPO_ENDPOINT_PUT/${PROJECT_NAME}/latest/vmlinuz
          curl -X PUT --upload-file ./undionly.kpxe \
            $REPO_ENDPOINT_PUT/${PROJECT_NAME}/latest/undionly.kpxe